language: php

sudo: false

php: 7.1

cache:
    directories:
        - $HOME/.composer/cache

env:
    - LOCALE=en SECRET=secret DATABASE_DSN='pgsql://postgres@127.0.0.1/travis_ci_test'

before_install:
    - npm install -g bower

install:
    - make

before_script:
    - php -S localhost:8080 -t web/ web/index.php &> /dev/null &

script:
    - ./bin/atoum
    - ./bin/behat -fprogress --tags='~@user'
