language: php

sudo: false

php: 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - php -S localhost:8080 -t web/ web/app_dev.php &> /dev/null &
    - ln -s parameters.yml.dist app/config/parameters.yml
    - make

script:
    - ./bin/atoum
    - ./bin/behat -fprogress --tags='~@user'
