language: php

sudo: false

php: 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - php -S localhost:8080 -t web/ web/app_dev.php &> /dev/null &
    - composer install

script:
    - ./bin/atoum
    - ./bin/behat -fprogress --tags='~@user'
