framework:
    assets: ~
    secret: "%env(SECRET)%"
    default_locale: "%env(LOCALE)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    templating:
        engines: ['twig']

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles: ['AppBundle']
    filters:
        cssrewrite: ~

pomm:
    configuration:
        default:
            dsn: "%env(DATABASE_DSN)%"
    logger:
        service: "@logger"
