imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
    profiler: ~

web_profiler:
    toolbar: true
    intercept_redirects: false
