imports:
    - { resource: parameters.yml }

framework:
    assets: ~
    secret: "%secret%"
    default_locale: "%locale%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    templating:
        engines: ['twig']

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug: "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles: ['AppBundle']
    filters:
        cssrewrite: ~

pomm:
    configuration:
        default:
            dsn: "%database_dsn%"
    logger:
        service: "@logger"
